From: Dennis Coffey (Tymcom-X Systems) <DenCoff@D35> 
Date: Thu, 17 Sep 87 15:35:57 PDT 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 

Guys,

    The connection to Tymnet on floor 3 of this building is O.K.!  I've talked
with Dick Kovachs about connecting to Tymnet through his engine.  No problem
-- except that Dick reminded me that we will have to run cable from his
printer room to his phone closet, and from our phone closet to our lab.  He
was concerned about the appearance of the cables.  We might be able to run
them up the (inside of the) walls and through the ceiling, since both ends of
the cable are in rooms with real walls, and I've looked at the ceiling:  it's
typical suspended ceiling.  We could pull cable just like Carl and I did at
Nicholson Way.

    We could be in Tymnet just as soon as the cable is pulled and connected,
and the code is cut!

-D.-
From: Joe Smith <JMS> 
Date: Fri, 18 Sep 87 23:53:36 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Micronet dialups are 922-6235 and 922-7432. 

1) The modems are connected to extensions 6235 and 7432.
2) X14 is currently running on the RP06 connected to X17.
3) The San Jose Public Outdial host is 2457.  See example below.

please log in: JMS:2457
TYMNET ASYNCHRONOUS OUTDIAL -- HOST 2457 -- SAN JOSE, CA
>DAIL 922-6235
Dialing...................
Call failed - no answer

>DAIL 922-7432
Dialing....
Connect 1200

G'Day Group, Welcome to TXSNET
We are an island!
-2770-013-
please log in: JMS:14;
host not available through net

please log in: JMS:17;;
proj code:
X14       This is the one-pack RP06 system in Nicholson Lane        X14
.EXIT

please log in:

It looks like someone disconnected the modem in the KL Library - 6235 was
working last night.  /Joe
Received: from F29.Tymnet by D35.Tymnet; Mon, 21 Sep 87 16:53:59 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 21 Sep 87 16:45:25 PDT
From: TYMOPS.TOMASI@EMSTXS.Ontyme.Tymnet 
Date: 22 SEP 87 00:08:47 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M20248@Ontyme.Tymnet 
Subject: NETWORK RESOURCES 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Thu, 24 Sep 87 13:02:33 CDT 
Resent-to: JMS, OSMAN, CARL, DENCOFF, FLETCHERC 

TO ALL SUPERVISORS:  PLEASE DISTRIBUTE THE FOLLOWING MESSAGE TO 
ONLY MANAGERS.  THANK YOU.

                 MCDONNELL DOUGLAS NETWORK SYSTEMS COMPANY

                     T Y M N E T    O P E R A T I O N S

                            M E M O R A N D U M



DATE>      21 SEP 87  15:50

TO>        ALL OPERATIONS PERSONNEL/TYMNET MANAGERS

COPIES>    P. KRETER  W. PRINCE

FROM>      BOB TOMASI


SUBJECT>   NETWORK RESOURCES


-----------------------------------------------------------------------



          I AM PLEASED TO ANNOUNCE THE APPOINTMENT OF THOM  KELLEY  TO  THE

          POSITION OF MANAGER,  NETWORK RESOURCES,  REPLACING JACK SNAVELY.

          THIS APPOINTMENT IS EFFECTIVE MONDAY, SEPTEMBER 28TH, 1987.


          WITH THOM'S APPOINTMENT,  SEVERAL CHANGES WILL BE TAKING PLACE IN

          THE  NETWORK  RESOURCES  GROUP.    FIRST,  THE LOGISTICS PLANNING

          FUNCTION, UNDER FRANK TROGLIONE,  WILL BE MERGED INTO THE NETWORK

          RESOURCES  GROUP AND WILL CONTINUE TO REPORT TO THOM.   THE ORDER

          PROCESSING GROUP, UNDER KATHERINE GOODWIN,  THE PROJECT IMPLEMEN-

          TATION GROUP,  UNDER BERYL AGUA, AND THE RESOURCE CENTER UNDER JO

          HANNAH, WILL ALSO REPORT TO THOM.   THIS COMBINATION OF FUNCTIONS

          WILL BETTER ENABLE US TO ADDRESS THE MATERIAL SUPPORT CONCERNS AS
                                                                Page  2


          THEY RELATE TO ORDER PROCESSING.   PEGGY MACDONALD,  SECRETARY TO

          JACK SNAVELY, WILL ALSO REPORT TO THOM.


          THIS  NEW  NETWORK RESOURCES GROUP WILL THEN REPORT INTACT TO DR.

          A.  S.  (RAJA) RAJARAMAN,  DIRECTOR OF NETWORK  PLANNING.    THIS

          CHANGE  IS  BEING  MADE  TO  CONSOLIDATE  REPORTING FUNCTIONS AND

          PROVIDE  A  MORE  COHESIVE  APPROACH  TO  NETWORK  PLANNING   AND

          IMPLEMENTATION.


          I  TRUST  THAT I CAN COUNT ON YOUR SUPPORT FOR BOTH THOM AND RAJA

          AS THEY ASSUME THEIR NEW ASSIGNMENTS.
Received: from F33.Tymnet by D35.Tymnet; Thu, 24 Sep 87 11:14:10 PDT
Return-path: <OSMAN@D35> 
From: Osman Guven <OSMAN@D35> 
Date: Tue, 8 Sep 87 14:11:36 PDT 
To: Karen Perrault <FSC.K/Perrault@Ontyme>, Craig Fletcher <FletcherC@D35> 
Subject: New part number .. 

Karen ..

	Here is the new part number for a diagnostic pack on a
KS-10(20/20) system.  Product support had to make a diagnostic pack
in early August to sent to Phonix.

KS-10(20/20) Diagnostic pack part number:
-----------------------------------------

TDSKS6-01	RP06 Diagnostic Pack
TDSKS3-01	RM03 Diagnostic Pack

-Osman Guven-
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@D35> 
Date: Thu, 24 Sep 87 17:42:11 PDT 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: Micro-net to public net connection. 

I saw and talked with Gary Pretty late this afternoon.  I asked him about
completing the sync line for the connection of 2770 to engine 5566.  He is
busy getting async and voice access to those who are moving this weekend, so
he cannot afford the man-hours needed to immediately finish the sync line for
us.

Gary said that our line should be finished early next week.

-D.-
From: Joe Smith <JMS> 
Date: Mon, 28 Sep 87 13:31:31 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Nicholson voice line is 432-1564. 

As of Monday morning, the following phone lines are connected:
  (408)432-1564 = voice line (Pacific Bell beige telephone)
  (408)432-1735 = TXS modem (with Pacific Bell yellow telephone)
  (408)432-0935 = MIS modem (with Radio Shack brown telephone).
The ringer on the Radio Shack phone cannot be heard above the noise of all
the fans, which is why a real telephone is connected to 432-1564.
/Joe
From: Joe Smith <JMS> 
Date: Mon, 28 Sep 87 22:07:59 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: F38 fixed. 

INFO stopcode "BADSAT" at 28-Sep 10:05 on BPA0 at page 264000
INFO stopcode "BADUFD" at 28-Sep 10:51
INFO stopcode "REDSAT" at 28-Sep 14:04 on BPA0 at page 264000
Hung BPA12,BPA15,BPB5,BPA7,BPA12,BPB7,BPA1,BPA15,BPA10,BPA1,BPA15,BPA6,
     BPA10,BPA3,BPA11,BPA15,BPB7,BPA4,BPA17,BPB4,BPB5,BPA14,BPB6,BPB7,
     BPA13,BPB4,BPB6
INFO stopcode "REDSAT" at 28-Sep 14:    (OPR terminal zapped at this point)
LOGINN not found

At this point they called us.  The RIB for [1,4].UFD was marked bad, the
self pointer was corrupted.  Carl and I fixed the RIB pointer using (MPL)FILDDT.
Tried to bring up system in MANUAL mode, but still "?LOGINN not found".
I went to Solar Way, came up REFLAGged to run TSTSUP.  Turned off the bit
which is set when the monitor finds a bad RIB, and (SYS).UFD was then OK.
Ran a full DSKCLN, answered at 19:41.    /Joe
From: Joe Smith <JMS> 
Date: Tue, 29 Sep 87 13:12:57 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: X32 disk gone. 

Osman says they overwrote part of our DSKB on the 3650s.  The last incremental
backup was done Friday night - any work done Sunday and Monday is gone.
From: Joe Smith <JMS> 
Date: Sun, 4 Oct 87 21:13:23 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: X32's console on F33. 

I called Fremont to see if the test KL was down for a particular reason.
They said the CTY on F33 started smoking, so they borrowed the LA36 from X32.
I suppose they don't have any other current-loop LA36's available.  /Joe
Received: from F29.Tymnet by D35.Tymnet; Thu, 24 Sep 87 15:44:19 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Thu, 24 Sep 87 15:25:33 PDT
From: HRD.TRNG@EMSTXS.Ontyme.Tymnet 
Date: 24 SEP 87 23:12:41 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A15625@Ontyme.Tymnet 
Subject: M&PD-San Jose address/phone 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Mon, 5 Oct 87 21:51:02 CDT 
Resent-to: fletcherc 

                     Management & Professional Development

                              M E M O R A N D U M


  TO:       All Employees (Please post)

  FROM:     Stephen Reynolds, Manager
            Management & Professional Development (M&PD) San Jose

  SUBJECTS: .4Q87 M&PD-San Jose Training Schedule
            .New M&PD-San Jose Address and Phone Numbers

  DATE:     September 24, 1987

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
  BAY AREA EMPLOYEES   
  -4Q87 M&PD-San Jose schedules, enrollment forms, and course descriptions
  were sent to all A-F managers (Sr. Section Manager and above) on 
  September 11.  See your manager for a copy.
      -Registrations are due back to M&PD-San Jose by September 28.

  EMPLOYEES OUTSIDE THE BAY AREA
  -4Q87 M&PD San Jose schedule, enrollment forms and course desctiptions
  will be sent to all District Managers and above during the week of
  September 28 forses in San Jose, Vienna/Rockville,
  Rosemont/Mt. Prospect, and San Diego.  See your manager for a copy.
      -Registrations are due back to M&PD-San Jose by October 12.

  FOR INFORMATION:
  - Tymnet Training & Education, call Cheryl McGowan at 408/922-7617
      (408/432-5042 until Oct. 5).

  - M&PD-St. Louis, call Linda Zink at 314/232-9304.

  - M&PD-Irvine, call Bonnie Watkins at 714/250-1000 ext.7486.

  - Denver (MDCIS) programs, call Kathy Padus at 303/220-6044.

*************  NEW M&PD-SAN JOSE ADDRESS  **************************

  Mail:  McDonnell Douglas Training Center
         2665 North First Street
         San Jose, CA  95134

  Interoffice:  CA59 Bldg T

  Ontyme:  HRD.TRNG

  Phone:  Name                      After 10/6/87              Until 10/6/87
          Stephen Reynolds..........408/922-7654............... 408/435-7742
          Kathleen Corcoran.........408/922-7651................408/432-5068
          LaVonne Hage..............408/922-7652................408/432-5292
          Belinda Quesada...........408/922-7653................408/435-7740
Received: from X32.Tymnet by D35.Tymnet; Tue, 6 Oct 87 11:22:28 PDT
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Tue, 6 Oct 87 11:21:11 PDT 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: This afternoon .. 

I am going to BLDG "C" to pack my books
this afternoon.
-Osman-
Received: from X32.Tymnet by D35.Tymnet; Tue, 6 Oct 87 11:31:58 PDT
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Tue, 6 Oct 87 11:30:57 PDT 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Group Meeting .. 

Our "Group Meeting" on Thursday mornning has been
rescheduled to Thursday 10/7 @13:00
-Osman-
Received: from X32.Tymnet by D35.Tymnet; Tue, 6 Oct 87 11:36:16 PDT
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Tue, 6 Oct 87 11:33:18 PDT 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Group Meeting 10/8 @13:00 

Our "Group Meeting" on Thursday mornning has been
rescheduled to Thursday 10/8 @13:00
-Osman-
From: Joe Smith <JMS> 
Date: Tue, 6 Oct 87 20:16:28 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: F26 survived a base reload! 

F26's base was having problems (many jobs running LOGINN in TI state) and
it was reloaded.  Host 26 was not available thru net because the EBUS base
was waiting for the PDP10 to tell it what host number to use.  From KLDCP
I was able to deposit a host-to-base message in the ORING specifying the
host number and 127 ports.  When ORPPDP was poked, host 26 became visible.
OPER could log in, but others couldn't because the base thought the PDP10
was SHUT but F26 thought it had answered.  Setting SCHED 400000 and SCHED 0
cleared up that misconception.  I will add the code to send the right
messages to SCNSER; it may be worth adding a DDT patch to all P035/C when
it's ready.  /Joe
From: Carl A Baltrunas <Carl> 
Date: Tue, 6 Oct 87 18:26:49 PDT 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Subject: Kudo's for F26 

Hurray... and another job well done...  We need to test the patch on X32
first, of course...
/Carl
Received: from X32.Tymnet by D35.Tymnet; Thu, 8 Oct 87 1:02:46 PDT
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Thu, 8 Oct 87 1:01:33 PDT 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Schedule .. 

	I would like to work from home for the next 2 days.  Our baby 
was admitted to the hospital last night and is expected to be there for 
severel days. They have diagnosed her as having septic arthritis and 
have started her on antibiotics.  My wife is going to be at the hopital 
most of the time and I will take care of the other kids at home.

	I know Friday we were planning to have a dry run of Monday's 
class.  Please go ahead without me. I will plan to teach the "HARDWARE"
section and it should take me about a day and a half.

	Call me at home or on the pager if you need me or have any questions.

-Osman-
From: Joe Smith <JMS> 
Date: Fri, 9 Oct 87 21:31:27 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: TYMNET moving into Nicholson 

There are 6 Engines in Nicholson Lane.  They are powered up, but not
connected to anything.  It appears that TYMNET has changed the combination
to the back door.  /Joe
From: Carl A Baltrunas <Carl> 
Date: Sun, 11 Oct 87 12:38:39 PDT 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Cc: Rick Daniels <DanielsR@F74.Tymnet> 
Subject: Schedule 10/12-10/16 

Joe,
  I called Osman on Saturday and he was still trying to juggle his schedule
to be available on Monday.  His daughter is not expected to be released from
the hospital until Tuesday sometime (if all goes well).

  I told him that we discussed doig the HARDWARE portion of the class without
him and if he couldn't make it, we would do it.  He was relieved, because it
would have been very difficult for him to make it to Fremont before Wednesday.
On Wednesday, he'll try to be there and cover anything we didn't cover in as
much detail as the class is interested.

  I will stop by the office today to pick up the KL handbook set and the three
volume KL handouts from Rhett's class, just so we will have them available.  I
will also bring the processor reference manual (unless you happen to already
have a copy at home, then you can bring it.  Let me know, so I can leave it at
the office.)

/Carl
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@D35> 
Date: Sun, 11 Oct 87 20:30:33 PDT 
To: (Monitor Group:), Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: My availability this week. 

Guys,

  Concerning teaching this week, Wednesday sounds ideal for me.  I'm going to
be at the Cal. Berkeley Extension seminar on UNIX System Administration on
Monday.  The Cal. Extension seminar will be all day, in Mountain View.  I'll
be checking TUMS, Aspen & Judy for messages.  It will be difficult to provide
user support Monday, but I'll do what I can about getting and answering
messages.

-D.-
From: Joe Smith <JMS> 
Date: Tue, 20 Oct 87 21:28:54 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Formatting X32's disks. 

I found 2 bugs in PAKCOP(PAKCP5).   
If the 1st string controller is off-line (BPA0-BPA7), then PAKCOP assumes
the entire 3674 controller is off-line (BPA0-17 & BPB0-17).  PAKCP5 didnot
want to look at the string of 3650 disks on BPA10-17 as a result of
the string of 3675 disk on BPA0-7 being switched off.

2nd problem: Although I tried to make PAKCOP do everything SA10NW does,
something is missing.  Those paacks have not been formatted using PAKCOP,
because PAKCOP dies on CYL 559 with "Equip Check".    They were formatted with
SA10NW with FMTM=0, wich does cylinders 0-554 only.  When I tried FMTM=1,
SA10NW aborted because cylinders 555-559 were not set up.  I am now using
FMTM=-1 to re-write HA and R0 - this takes 2 secons per cylinder, 19 minutes
per pack.  After SA10NW finished, thhen I reformat thhem in pages.
I plan do do all but BPA16 - I'll leave that one as a test case for the
next version of PAKCOP.			/Joe
From: Joe Smith <JMS> 
Date: Tue, 20 Oct 87 22:45:38 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: X32 down - PAKCP5 broken. 

Something is wrong with the current version of PAKCOP - it won't
format at all.  I will investigaet tomorrow.  /Joe
From: Dennis Coffey (Tymcom-X Systems) <DenCoff> 
Date: Wed, 21 Oct 87 13:29:11 PDT 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: Leased line troubles. 

Yesterday afternoon I went to Nicholson Way, to look at possible modem
problems.  Our Paradyne modem was powered down.  I turned the power back on
for it.  The indicator LEDs were lit for the 3 left-most indicators and the 1
right-most indicator.  The 4th from the left, which Joe tells me is carrier
detect, was not lit.

I returned to D-2.  The modem in the lab was indicating the same state.  I
tried to load 2770 from the public network, but it wouldn't take a load (it
"timed out", according to LOADII), which should indicate that it was already
loaded fine.

While at Nicholson Way, I neglected to look at the connection between the
Paradyne modem and the leased line.  If it was disconnected when the line was
being worked on Monday (which is highly possible, since they were there and
had powered the modem down) that could be a cause for the communication
failure.

Or (paranoid fantasy):  Tymnet is messing with us, because we have a
non-Tymnet line going into "their" "super site".  (Remember the fortune
cookie:  "Just because you're crazy doesn't mean they're not out to get you.")

-D.-
From: Joe Smith <JMS> 
Date: Thu, 22 Oct 87 1:45:40 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Nicholson Modem working now. 

The 9600 baud modem is in the rack by the F3's, but the leased line interface
is on the other side of the ramp, by the 2020's.  The modular plug at the
interface end was unplugged.  It was not obvious because the it was hidden
by the blue panel.  It has been moved to the back of that rack to be more
accessable - the link came up as soon as it was plugged in.

Host 17 was down to allow Osman to build another KLAD pack on the RP06,
host 14 was brought up but is not visible to the Supervisor due to 2770's
config file.  Until that's fixed, the only way to get to the 2020 that is
host 14 is by dialing (408)432-1735.  It is up now, on the 1-pack RM03.
/Joe
From: Joe Smith <JMS> 
Date: Thu, 22 Oct 87 1:59:02 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: X32 on three 3650s in blocks. 

So that we can all have something to work with, I have formatted 3650's using
SA10NW (BPA10,BPA11,BPA12) and restored X32's files on them.  This way we can
get to our files and I can load PAKCP5 from disk to test it on the other 5
disks.  PAKCOP (all versions) is getting EQUIP CHECK - SYNC OUT ERROR on this
particular string of HDAs.  I plan to add code to type out the 3650 specific
portions of the sense bytes when this occurs.  /Joe

From: Osman Guven <OSMAN@X35> 
Date: Thu, 22 Oct 87 8:57:53 PDT 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Opeartion Class Evaluation .. 

=====================================================================

From: OPERA.SUP@EMSTXS.Ontyme.Tymnet 
Date: 22 OCT 87 00:13:00 
To: TXS.O/GUVEN@EMSTXS.Ontyme.Tymnet 
Message-id: A25027@Ontyme.Tymnet 
Subject: "a. HOW DO YOU FEEL THE SEMINAR"... 

a.  HOW DO YOU FEEL THE SEMINAR WAS PRESENTED?

    THE SEMINAR WAS PRESENTED IN A WELL-ROUNDED MANNER.
NOT ONLY DID THE CLASS LEARN ABOUT BASIC OPERATOR FUNCTIONS
AND THIER IMPORTANCE, BUT ALSO THE FUNCTIONS OF SOFTWARE
SUPPORT AND FIELD SERVICE AND THE WAY IN WHICH ALL GROUPS
INTERACT WITH ONE ANOTHER.

b.  DO YOU FEEL THE SEMINAR SHOULD HAVE BEEN LONGER?

    THE SEMINAR ON THE 10'S LASTED ONE WEEK.  THE AMOUNT OF
MATERIAL COVERED SEEMED TO BE SUFFICIENT. ALTHOUGH CLASS WAS
DISMISSED EARLY EVERYDAY (WHICH THE OPERATORS DIDNT MIND)
SOME OF THAT TIME COULD HAVE BEEN PUT TO MORE USE.

c.  WHAT DID YOU GET OUT OF THE SEMINAR?

    THE SEMINAR PRESENTED MUCH INFORMATION THAT PEOPLE WERE         
UNAWARE OF. FOR EXAMPLE: DIFFERENT COMMANDS AND THIER MEANINGS,
HARDWARE CONFIGURATION AND THE IMPORTANCE OF UNDERSTANDING IT,
DAILY DUTIES AND AN IN DEPTH EXPLANATION OF WHY THEY ARE DONE.

d.  INCLUDE OTHER COMMENTS YOU FEEL ARE PERTINENT.

    OVER ALL, THE PDP10 SEMINAR WAS GOOD.  IT LED ME TO UNDERSTAND
THE SYSTEM BETTER AND THE ACTUAL IMPORTANCE OF MY JOB.  ALTHOUGH
THE FIRST SEMINAR DID COVER A LOT, THE INSTRUCTORS MIGHT WANT TO THINK
ABOUT SPENDING MORE TIME ON BASIC COMMANDS (ESPECIALLY THE BT COMMAND)
AND ALSO HARDWARE  CONFIGURATION.

=====================================================================

This is the class evaluation from Rick Daniels.  It looks good.

-Osman-
From: Joe Smith <JMS> 
Date: Fri, 23 Oct 87 22:22:09 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Where the files went 

Before move:  All TXS files were spread out on 3 systems: X930, X62, X95.

Liberty St:  All of X930 and X62 files were combined onto one system.
  This system was called X118 and consisted of 3 RP06 packs.  It had
  everything that X930+X62 had, except for the directories Carl saved
  on the "ripoff" tape and directories (such as KS2020) which were
  kept on the 2 RM03 X95 system instead.

During move:  Everything was moved to X32 in Solar Way.  X32 used 4 3675
  packs, and had X118's RP06 save restored to it.  To make sure nothing got
  lost, the saves for X930, X62, and X95 were also restored.  Some of the
  ripped off directories came back as a result of this.

After move:  A one-pack RP06 system was build on X17 from the 1-tape save
  and Carl's 4-tape save and the microNET sources from B39.  A one-pack
  RM03 system was built on X14 from the 1-tape save only.

23-Oct-87:  A third RM03 was added to X95's 2-pack set and mounted on X14.
  All the files that Carl had on the 1-pack RP06 system are being restored
  to it.  X14 will have KS2020 and microNET related files.
  The 3-pack RP06 set has been formatted and is being restored to the way
  it was when it was in Liberty St.

Future:  Directories which exist on X17 and X14 need to be sorted out.
  Between the two of them, they have enough space to handle everything
  that is currently on X32.  A 1600bpi save of X32 can then be restored
  to the two 2020s.
From: Joe Smith <JMS> 
Date: Sat, 24 Oct 87 9:19:53 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Hotline call - TELECO fails with F26-P035/C03. 

Contact: Fremont Operations, (415)498-2588, David Jorgenson, System 26
Problem: Users called in complaining that TELECOPY does not work.
         "TRANSFER ABORTED DUE TO CONTROLLER TRAP" or "NO RESPONSE".
Fix:     Told them to go back to SYSTEM.SAV with F26-P035/C.

This bug is now high priority.  It might affect F22 or F74 running /C03.
			/JMS
From: Joe Smith <JMS> 
Date: Sun, 25 Oct 87 14:41:27 CST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff, DANIELSR@F26, RICHARDSON@F26 
Subject: TELECO not working (again) on F26. 

Contact: Fremont Operations, David Jorgenson, F26
Problem: TELECO got "TRANSFER ABORTED DUE TO CONTROLLER TRAP" on recieve and
         "CIRCUIT NOT RESPONDING" on sends.
         They were running P035/C.

Work:    Tried reloading P035/C, no luck.  Tried P035/B07 from OLDMON, no luck.
         Tried reloading F26's base, no luck.

         Created special TELECO.SAV with DDT and breakpoint at location TRAP.
         Failure was caused by recieving a null character.  Modified BIO.MAC
         to output in hex all characters read from block I/O input buffer.
         Ran on X32 to get good data, compared with run on F26.  Found
         null characters in input buffer - all non-null characters were good.
         Log is (TSUCOOP:26)TEL0.LOG

Block I/O not working.  Maybe base needs ECO?  Will look at it Monday.  /JMS
From: Osman Guven <OSMAN@X35> 
Date: Wed, 28 Oct 87 9:44:20 PST 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Class Evaluation .. 

Here is an other class evaluation from Sharon Marcotte.
-Osman-


===============================================================================

Subject: TYMCOM - 10 SEMINAR 

DATE> 27 OCT 87
 
FROM> SHARON MARCOTTE
 
TO>   RICK
 
CC>   CHERYL
 
SUBJ> TYMCOM - 10 SEMINAR
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
Rick,
 
Here is my feelings on the TYMCOM-10 training class:
 
A) I feel that the information was well grouped. The instructors did not teach
   as if the students were all programmers, like in most cases.
   The presentation for the most part was well structured, the only obvious
   problem I felt was the fact that the people who were training did not get
   to prepare for the class, due to the personal problems of Osman & Joe.
   For example: The first day Osman was to teach and he had to attend to
   personal business which left Carl & Joe fairly unprepared to teach that day.
 
B) I feel that as far as time constraints that the training should have been
   on a more rigid schedule. Breaks on the hour for 10 minutes, lunches 1 hour,
   class starting and ending as scheduled.
   One week was fine for the duration.
 
C) I refreshed on a lot of items that I had forgotten, unfortunately I missed
   more than I wanted to, but I will be attending the next session.
 
D) All in all I feel that it was a valuable training session.

==============================================================================
From: Joe Smith <JMS> 
Date: Wed, 28 Oct 87 17:09:06 CST 
To: DERNST@39 
Cc: Monitor Group <JMS>, Carl, Osman, FletcherC, DenCoff 
Subject: Simultaneous node errors. 

Yesterday, I rerouted power at Nicholson Lane.  I reloaded node 2346 last,
and expected the date and time to come in from the Supervisor as soon as it
started to node 2770.  Instead, the following happened:

27-Oct-87 15:05 2020 host 17 died with ?PAR ERR 373 001, node 6657 OK
27-Oct-87 15:05 2020 host 14 died with ?PAR ERR 373 001, node 6760 OK
27-Oct-87 15:05 node 2346 died with Fatal node error BPT
27-Oct-87 15:05 node 2770 died with Fatal node error CSE
----------------------------------------------------------
G'Day Group, Welcome to TXSNET
You want modems?  We got modems!
-2346-004-
please log in:
Fatal node error BPT
Registers:
  177740  156500  001374  000004  131402  141134  150364  021166  000001
150364:  106214  014626
Debug:
  000000  000000  000000  000000  000000  000000  000000  000000

5
 130374
@
----------------------------------------------------------
G'Day Group, Welcome to TXSNET
We are not an island!
-2770-004-
please log in:
Fatal node error CSE
Registers:
  130164  000000  000004  000000  000000  000000  146460  014042  000000
Stack:
146460:
Debug:
  000000  000000  000000  000000  000000  000000  000000  000000
----------------------------------------------------------

It looks like the "DP parity error" (373) was caused by bad data from the
KMC as a result of 2346 sending garbage to the two bases.  Very strange.
From: Osman Guven <OSMAN@X35> 
Date: Fri, 30 Oct 87 19:41:31 PST 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Class Evaluation .. 

Here is an other "Class Evaluation"

===============================================================================

Date: 29 OCT 87 09:07:00 
To: TXS.O/GUVEN@EMSTXS.Ontyme.Tymnet 
Subject: PDP10 Class Evaluation 

DATE> 29 OCT 87
 
FROM> Jim Wallace
 
TO>   Rick Daniels
 
SUBJ> PDP10 Class Evaluation
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
 
      a. How do you feel the seminar was presented?
COMMENT: Due to circumstances the order of the classes had to be changed,
         this did have an effect on the big picture goal of the class since
         it meant others had to be called upon before they were ready. The
         class was also prepared for those who had some experience, yet the
         participants were mainly made of inexperienced persons. These two
         things lessened the effect of the class, however, I thaught the
         classes were very informative.
 
      b. Do you feel the seminar should have been longer?
COMMENT: The seminar really couldn't have been any longer because of
         scheduling problems. I do think that we need to go into detail
         in some areas, in another seminar. A sequel of sorts.
 
      c. What did you get out of the seminar?
COMMENT: I picked up bits and pieces of information from all areas covered.
         I now feel more comfortable with the file structure, and monitor
         concepts inparticular.
 
      d. Include as other comments you feel are pertinent.
COMMENT: Next time we should match the information and class objective with
         the expected participants of the class. I was very satisfied with
         what Lynn and myself took from the class, but the new people will
         probably need to reattend the class once they've worked with the
         PDP10's for a while. Rick I commend you on your part in making
         these classes happen.

===============================================================================
From: Osman Guven <OSMAN@X35> 
Date: Mon, 2 Nov 87 17:06:04 PST 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: EBUS E.C.O and /C03 .. 

FOR YOUR INFO ..
I got this mail from Rick and he got it from Tom M.  There seems to be
some confusion: (a)What EBUS E.C.O did to resyncing BASE with the PDP10
(b)What systems running with /C03 monitor, resync patch and (c)What are
the resync condition that /C03 will handle.  I have showed to Rick how
/C03 monitor resyncs with the BASE.  -Osman-
===============================================================================

Osman;

Received the below from T. Marconi - is there anything I have to do,
other than figure it out and inform Operators?

Thanks Rick

--------------------------------------------------------------------

 
                  I  P  S     M  E  M  O  R  A  N  D  U  M         
 
 
   Date: FRIDAY , 10/30/87 12:05:33
 
   To: Rick Daniels
       Jerry Meyer
 
   Cc: Ed Barens
       Bill Fischer
       Ed Roop
       Leland Yarbrough
       Dallas Shift supervisors
 
   From: Tom Marconi
 
   Subj: DECsystem10 P035/C monitor with E-BUS uprev.
   ----------------------------------------------------------------------
     As of today  10-30-1987 all of the Dallas  DECsystem10's are running
   with the  P035/C monitor and the  uprev E-BUS Tymnet board.  With this
   combination we have  seen a drop in NOBASE type  stopcode crashes that
   took the DEC system and the engine  down. With this added value to our
   system, we should see a much needed improvment of CPU reliability.
 
     The CTTY will report the following messages:
 
      %%EVENT stopcode NOBASE at dd-mmm-yyyy hh:mm:ss
      No response from base. Please reload it. PDP-10 is still up.
 
     After the  base is reloaded  or reinit the  DEC system and  the base
   will resync and you will receive the following message twice:
 
      %% EVENT stopcode BASEOK at dd-mmm-yyyy hh:mm:ss
      Code in base is version 2.00 - debug flag is OFF
 
     I wish we had this 5+ years ago.  In any case, this is much like how
   the TYMCOM-370 base/operating system works. If the DEC user has LOGOUT
   on DISCONN, no problem, the user is  logged off the system, but if the
   user has DETACH  on DISCONN this will  put him in a  detach state.  If
   and only IF  the user is smart  they will reattach to  the detach job.
   If the user does not, we will start getting a bunch of control C jobs.
   We can do several things to correct these massive control C's,
 
      1) Change all users to DETACH ON DISCCON with a 15 MINUTE TIMEOUT
      2) Re-educate the user on how and why to reattach.
      3) Keep everything the same and run the FREE program.
 
     I have talked with OSMAN and as of Monday we are going to submit the
   FREE to run  all the time in detach  and kill all the  control C jobs.
   This is just for short term until whom  ever can come up with a better
   solution.
 
     As we all know, this should not be  coded as a crash nor recorded in
   the MUR  database, but FSC  should be  notified for the  simple reason
   that  the base  may have  a  problem and  may  need to  correct it  on
   schedule time.
 
    Any futher questions or comments, please either call me or send me an
   ONTYME.
 
                                 Thank you,
                                Tom Marconi

===============================================================================










From: Carl A Baltrunas <Carl> 
Date: Sun, 8 Nov 87 23:54:59 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Cc: William R Soley <WRS@B39.Tymnet> 
Subject: NONAME version %42(22) 

There is a new version of NONAME which has a variety of things changed
in it, in particular allowing different changes to be made depending on
your status.  Of course, all that horrid white-space has been flushed
away in favor of a more user friendly scanner.

New features for Roy Roskilly - Autologout may be set, however no limit
                                is currently available although there is
                                room in the district word for it...

New features for security     - Logout on stop may be set/cleared
                                requires an account-supervisor to do this

                              - Restricted Command Mode may be set
                                requires an account-supervisor to do this

/Carl

Release will occur after some beta-testing by Roskilly.
From: Carl A Baltrunas <Carl> 
Date: Mon, 9 Nov 87 0:03:02 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Cc: William R Soley <WRS@B39.Tymnet> 
Subject: Autologout changes 

Again... to aid in implementing Roy Roskilly request the monitor commands
which affect the user's incativity time-out have been modified to allow
anyone to set a limit between 1 and the system default limit.  However, to
set the limit to 0 or to a value greater than the system default, you MUST
be an account supervisor or (have OP, WC or JL license, since anyone with
these licenses can change their limits by mucking around).

Affected areas:
   SET AUTOLOGOUT n           0 < n <= system-default   anyone
                              n=0 or n > system-default supervisor or license
   SET NOAUTOLOGOUT           same as SET AUTOLOGOUT 0 -- see above

   SETINA UUO                 same as commands above

Unaffected:
   SET DEFAULT INACTIVITY n   requires OP license to set/change system-default


/Carl
Received: from X32.Tymnet by D35.Tymnet; Fri, 13 Nov 87 9:17:21 PST
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Fri, 13 Nov 87 9:16:13 PST 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Meeting is at 11:00 today .. 

Metting is rescheduled.
From: Joe Smith <JMS> 
Date: Sat, 14 Nov 87 23:32:00 CST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: C05 working. 

A minor typo was found in /C05 which caused LDBLOG to report the wrong node
number on PTYs (such as SUBMIT jobs).  (M33)C05.PAT has been applied to all
copies of ##XC05.SAV and to NEWMON.SAV on all Fremont systems.  74XC05.SAV
had to be rebuilt with 127 jobs instead of 128 to handle 4 strings of 3675
disks.  We expect P035/C05 on all Fremont machines on Sunday.  /Joe
From: Joe Smith <JMS> 
Date: Sat, 14 Nov 87 23:37:43 CST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Backup save done - (NOBACKUP:32)INC.NOV 

I did an incremental save of X32's disks tonight before the power shutdown.
As usual, the tape directory is stored in directory NOBACKUP.  /Joe
Received: from F29.Tymnet by D35.Tymnet; Mon, 2 Nov 87 10:03:16 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 2 Nov 87 9:58:05 PST
From: NETS.TTE@EMSTXS.Ontyme.Tymnet 
Date: 02 NOV 87 17:32:54 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I06734@Ontyme.Tymnet 
Subject: TTE 1st Qtr Schedule 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Sun, 15 Nov 87 0:10:57 CST 
Resent-to: JMS, OSMAN, CARL 
Resent-cc: DENCOFF, FLETCHERC 
TTE1stQuarter88Schedule: 

                            M E M O R A N D U M

                          NETWORK SYSTEMS COMPANY
                         NETWORK SYSTEMS MARKETING


DATE>      30 OCT 87  13:17

TO>        The World

COPIES>    

FROM>      Tymnet Training and Education


SUBJECT>   TTE 1st Quarter 88 Schedule


-----------------------------------------------------------------------


The Tymnet Training and Education schedule for the 1st quarter '88
is now available via ontyme  :EXEC *** TTE.ENROLL

As a result of your feedback after class and the recommendations of the
training advisory task forces we have made some changes in our
courses.

  1.  The length of  TTE 455 Utilities Code Generation has been
      increased to 8 days to provide more time for hands-on labs.

  2.  SmarTym has been added to the TTE 230 Tymnet 3270/CMT/SmarTym
      course and the length has been extended to 8 days.

  3.  The name of TTE 260 has been changed to Async Error Correction, we
      now cover X.PC, Network Server, Menu Server and 2 new
      protocols - MNP & AFT

  4.  The CPU III, MAC III and Nano engine were added to the TTE 330
      TYMNET Hardware Maintenance and Troubleshooting.

  5.  The requirement for either TTE 455 or TTE 445 as a prerequisite 
      for TTE 450 has been revised.

The enrollment procedure remains the same - use  :EXEC *** TTE.ENROLL
In the last quarter we had some students show up who were not on our
roster.  Please be sure to send an enrollment form at least 5 weeks 
before your class.  That way we will be sure we have enough materials
and lab equipment available for you.  You should receive confirmation of
your enrollment within 2 days of your registration.

We look forward to seeing you in class next quarter.  If you have any
questions about the schedule or prerequisite courses, please give us a
call.  Our new phone number is (408) 922-7620


Sincerely,

Robert C. Grandey
Received: from F29.Tymnet by D35.Tymnet; Tue, 3 Nov 87 13:25:42 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 3 Nov 87 13:24:29 PST
From: OPERA.SUP@EMSTXS.Ontyme.Tymnet 
Date: 03 NOV 87 21:01:42 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A28777@Ontyme.Tymnet 
Subject: "MCDONNELL DOUGLAS INFORMATION"... 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Sun, 15 Nov 87 0:11:53 CST 
Resent-to: JMS, OSMAN, CARL 
Resent-cc: DENCOFF, FLETCHERC 

                            MCDONNELL DOUGLAS
                      INFORMATION PROCESSING COMPANY
                             4340 Solar Way
                         Fremont, California 94538
                             POWER SHUTDOWN

Time and Date Scheduled Down (PST or PDT)?  2300, 14 NOV 87 (PST)
Time and Date Scheduled Up (PST or PDT)..?  0700, 15 NOV 87 (PST)





The following ONTYME Hosts are affected:

515(B), 832(A), 1304(C), 2256(D), 2257(F), 2258(E),
2259(G), 2260(H), 2261(I), 7148(J), 7150(K), 7152(L),
7153(M), 7154(N), 2287(O), 2288(P), 2289(Q), and
2859(Z)

The following RAILTRACK Hosts are affected:

114, 555

The following ONTYME Utility Nodes are affected:

5321

The following OUTDIAL Hosts are affected:

4258, 834, 919

The following BISYNC VM Hosts are affected:

590 and 7246

The following TYMCOM-10's are affected:

F22, F26, F29, F30, F33, F38, B39, F58, F74

The following RAM Systems are affected:

6914 and 6915

The following NETVAL System is affected:

5514

The following OFFICE Systems are affected:

OF4-1087, OF1-1088, OF8-1643



Reason:  

>P G and E will be working on the street power during this time frame.
>

Please adjust your processing schedule as necessary.

Thank You, 
Fremont Computer Operations  <MDCISG IPC>                              
(415)498-2588 or Ontyme OPERA.BATCH
From: Dennis Coffey (Tymcom-X Systems) <DenCoff> 
Date: Sun, 15 Nov 87 16:33:32 PST 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: Temporary absence from office. 



                                  MEMORANDUM


                                                              TYMCOM-X SYSTEMS

DATE:  15-Nov-87    16:34:44    

  TO:  Craig, Carl, Osman & Joe

FROM:  Dennis Coffey  (Tymcom-X Systems)

SUBJ:  Delayed arrival Monday.

------------------------------------------------------------------------------

Guys:

	There have been a few problems around here, that I must stay home
Monday morning to try to get fixed.  I will not be arriving until I have
gotten the minimum fixed, or at least started.  Item on my list:

	1.)  Repair the U-joint on my car which broke Saturday, so it can move
under its own power and thereby get me to work.  (Car is currently in my
driveway.  I am unable to find a replacement U-joint.  The car must be out of
the driveway Monday morning, to make room for the 40 cubic yard "dumpster"
which will be placed to receive the old roofing shake and other construction
material/debris which is scattered throughout the house and yard.)

	2.)  Hire someone to dig up my front lawn, to find and fix the place
in the main sewer line from the house which is broken and since Saturday will
not allow anything to flow.  (I miss clean clothes, a shower and a toilet.)

	3.)  Be here to meet the roofers Monday morning.

	4.)  Finish wiring the kitchen and installing the range hood vent
through the ceiling and roof, so the kitchen ceiling drywall can be finished
and the new roof can be installed with the vent included.

	Items 1, 2 & 3 will be taken care of Monday morning.  Item 4 is a
project for tonight.

	-D.-
Received: from X32.Tymnet by D35.Tymnet; Mon, 16 Nov 87 0:19:03 PST
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Mon, 16 Nov 87 0:17:23 PST 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: On call .. 

I am on call 11/16 to 11/22  -Osman-
From: Carl A Baltrunas <Carl> 
Date: Tue, 17 Nov 87 14:38:58 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Subject: Schedule 

  I haven't been feeling well the past couple of days.  I was running a fever
Sunday night and yesterday and felt rather weak.  Today, feeling better but
still a little weak.

  I expect to be in for the meeting at 10am on Wednesday.  Will be doing a
little work from home today.  Send mail or call me if anything important
comes up.

/Carl
Received: from X32.Tymnet by D35.Tymnet; Tue, 17 Nov 87 20:13:05 PST
Return-path: <JMS@X32.Tymnet> 
From: Joe Smith <JMS> 
Date: Tue, 17 Nov 87 19:56:26 PST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff, WRS 
Subject: Progress in "slot out of ports". 

(SYS:26)CRA003 is a dump from F26 getting an IME stopcode after the base
was INITted.  The dump showed many terminals with the same set of messages
to be output.  They were (in order) "set echo mode", "read terminal
characteristics", "set terminal characteristics", "send a zapper",
"send defered echo", and "send orange ball".

Based on that, I created RCVZAP.PAT which clears out any other output
bits when a zapper is received from TYMNET.  This was applied to the
monitor on F26 and F33.

This afternoon, F26 ran out of ports again.  This time, (MPL)TTYTAB reported
only 1 port marked "zapped" and "gone".  All the other ports that the
dispatcher reported as "in cleanup" appeared to be correctly zapped from 
the host side.  However, when I set the bit which says to send a zapper,
nothing happened.  This evening I noticed that one of the lines in question,
TTY2:, was marked as being a PTY.  This caused zappers going out on TTY2
to be received by TTY3 instead of the base.  I have no idea how the PTY
bit got set, but I have added code to check and correct it to SCNSER.

I have created 26XC06.SAV and 33XC06.SAV with the SCNSER changes.
In addition, I created (MPL)HANGEM.SAV which will hang all ports that
are not logged in.  After running it on F26, all dispatcher ports that
had been in cleanup were freed.

P035/C06 has been copied to NEWMON on F26 and F33 and should be run
the next time they get slot out of ports.  /Joe
Received: from F32.Tymnet by D35.Tymnet; Thu, 19 Nov 87 21:13:33 PST
Return-path: <Carl@F32.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Thu, 19 Nov 87 21:09:11 PST 
To: Monitor Group <CARL>, Osman Guven <Osman>, Joe Smith <JMS> 
Cc: Craig Fletcher <fletcherc>, Dennis Coffey <dencoff> 
Subject: Micronet-TXSNET nodes 

We are now testing a neww configuration!
  Node 2770 is now an 11/03-SE box with a DUV, DLV and DRV to servve
as the interface to TYMNET at MDC-SJ.
  Node FRED is now a NETCON box with 2770's old configuration with
the exceptioon that it doesn't talk to TYMNET, instead it talks to 2770.

This shouuld allieviate the probles we see with both jitter and lost
circuits between TXSNET and TYMNET.  TELECOPY should work better...
Any problems please let me know.

/Carl
Received: from F29.Tymnet by D35.Tymnet; Tue, 17 Nov 87 14:04:18 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 17 Nov 87 13:56:23 PST
From: ISGFM.R/KAMINSKI@EMSTXS.Ontyme.Tymnet 
Date: 17 NOV 87 21:31:26 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: J40902@Ontyme.Tymnet 
Subject: "ADMINISTRATIVE NO: DIS-87-019"... 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Sat, 21 Nov 87 16:34:37 CST 
Resent-to: JMS, OSMAN, CARL 
Resent-cc: DENCOFF, FLETCHERC 



                                ADMINISTRATIVE          NO:    DIS-87-019
                                    BULLETIN            DATE:  17 NOV 87

         MCDONNELL DOUGLAS DIVERSIFIED INFORMATION SYSTEMS COMPANY



To:                ISG Lists B - E

Subject:           NEW ORGANIZATION FOR MDIPS PRODUCTION SERVICES,
                   ST. LOUIS



Effective immediately, the following organization is in place within
Production Services, St. Louis.

Ron Brown is Manager of IBM Processing Services, with responsibility for
mainframe and tape operations, print operations and distribution,
production job management, storage management, validations and security
management.

Gene Stephens is Manager of Specialized Processing Services, with
responsibility for Tandem, DEC, VAX and KL10 operations, ULTRIX
processing, and other special processing support activities requested by
MDISG business units.

Alice Diehl is Senior Section Manager in charge of St. Louis Processing
Change Management with responsibility for change control, daily planning,
hardware planning, problem management and hardware maintenance management.

Alice, Gene and Ron will report to the undersigned.  Your support of them
in their assignments will be appreciated.





Luke R. Abkemeier, Director
Production Services, St. Louis


CONCURRENCE:





Karen S. Gedera, Director
Information Processing
Received: from X32.Tymnet by D35.Tymnet; Sun, 22 Nov 87 23:57:21 PST
Return-path: <Carl@X32.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Sun, 22 Nov 87 23:56:04 PST 
To: Monitor Group <CARL>, Osman Guven <Osman>, Joe Smith <JMS> 
Cc: Craig Fletcher <fletcherc>, Dennis Coffey <dencoff> 
Subject: On call 

I am on call this week Nov 23-29th.   /Carl
From: Carl A Baltrunas <Carl> 
Date: Mon, 23 Nov 87 0:06:19 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Subject: On Call 

I am on call Nov 23-29.

/Carl
Received: from X32.Tymnet by D35.Tymnet; Mon, 23 Nov 87 19:16:00 PST
Return-path: <JMS@X32.Tymnet> 
From: Joe Smith <JMS> 
Date: Mon, 23 Nov 87 19:06:52 PST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff, Bill Soley <WRS@B39>, QSATS.G/Bubsey@Ontyme. 
Subject: Found bug causing loop in SCNSER. 

The two crashes on F26 indicated that SCNSER was looping when it tried to
report a black-ball to a PTY.  When too many characters were in the input
buffer, a bit was set to tell the PTY of the buffer overflow.  The routine
that delivered this message had a coding error, which meant the bit was
never cleared.  SCNSER would see this next time it ran - causing a loop.

This might be caused by a job running the COM program and forcing more than
1104 characters into the job's own input buffer.  The P035/C07 monitor will
output a stopcode whenever this occurs again.  /Joe
Received: from X32.Tymnet by D35.Tymnet; Tue, 24 Nov 87 12:50:16 PST
Return-path: <JMS@X32.Tymnet> 
From: Joe Smith <JMS> 
Date: Tue, 24 Nov 87 12:08:39 PST 
To: Bill Fischer <IPC.B/Fischer@Ontyme>, Cheryl Eldred <IPC.C/Eldred@Ontyme>,
	Rick Daniels <IPC.R/Daniels@Ontyme>, Ed Roop <IPC.E/Roop@Ontyme>, Ed
	Barens <IPC.E/Barens@Ontyme>, Jim English <IPC.J/English@Ontyme>,
	Leland Yarbrough <IPC.L/Yarbrough@Ontyme>, Tom Marconi
	<IPC.T/Marconi@Ontyme> 
Cc: Monitor Group <JMS>, Carl, Osman, FletcherC, DenCoff, SALTYRON@B39, wrs 
Subject: "slot out of ports" caused by AFD. 

F26 has two crash dumps taken when no commands could be typed on any
terminal.  Both were during a "slot out of ports" condition, and in both
cases, someone was executing a PCOM job that was running AFD.  The system
hung by a command like "RUN AFDCOM;AFDPUT.TMP" because the input file
had more than 1024 characters.

We have been trying to warn everybody for over 3 years that programs like
(UTIL)COM and AFDCOM should not attempt to force the input of more than
one line of 72 characters.  Anything over 72 characters cannot be guarenteed
to work.  Any procedure that needs more input must be converted to use the
":COM filname" feature of PCOM and SUBMIT if it is to be relied upon.

Daily procedures that use the COM program (such as running accounting for
BILLING10) should be converted to PCOM style control files before the next
monitor release.  Documentation is in (*6NEWS)PCOM.DOC.

		Joe Smith
		TYMCOM-X Support Group
Received: from F33.Tymnet by D35.Tymnet; Mon, 30 Nov 87 0:26:40 PST
Return-path: <JMS@F33.Tymnet> 
From: Joe Smith <JMS> 
Date: Mon, 30 Nov 87 0:20:03 PST 
To: Richardson, DanielsR 
Cc: Monitor Group <JMS>, Carl, Osman, FletcherC, DenCoff 
Subject: We can't log into system 32 - neighbor's TYM file changed. 

I have been unable to login into system X32 running on the spare KI.
Someone changed the TYM files for the two neighbor nodes on 25-Nov, and as
of 26-Nov-87, nodes 2275 and 2276 have declared node 4525 to be illegal.

Node 2276 reloaded at 330:12:51:09 = 26-Nov-87 at 04:51am PST
Node 2275 reloaded at 330:10:46:14 = 26-Nov-87 at 02:46am PST

334:08:10:03 7FC4  69: NO LINK FOR NEW LINE - LN= 00  NEIG= 04525
334:08:10:03 7FC4  20: LINE SUSPENDED - SEC'S= 0120  LN= 00  NEIG= 04525

(TYMNET)BK2275.TYM			(TYMNET)ND2275.TYM 25-Nov-87 08:52
1) : VERSION 5.21 26-OCT-87 BIS		2) : VERSION: 5.21 16-NOV-87 KLG
1) : ORDER #: CHANGE H/W TO M/S PER EDS	2) : ORDER #: 38448W.EB
1) : LOAD DATE: 26-OCT-87 MAC III	2) : LOAD DATE: 25-NOV-87 MAC III
**************
1) NLINES EQ $A 9			2) NLINES EQ $A 8
**************
1) TIILNK(4525,8,8)			2) TIILNK(2100,8,8)
1) TIILNK(2100,8,8)

(TYMNET)BK2276.TYM			(TYMNET)ND2276.TYM 25-Nov-87 08:53
1) : VERSION 5.21 01-OCT-87 CMK/BIS	2) : VERSION: 5.21 16-NOV-87 KLG
1) : ORDER #: 36900.WEB			2) : ORDER #: 38448W.EB
1) : LOAD DATE: 08-OCT-87 MAC III	2) : LOAD DATE: 25-NOV-87 MAC III
**************
1) NLINES EQ $A 9			2) NLINES EQ $A 8
**************
1) TIILNK(4525,8,8)			2) TIILNK(6415,8,8)
1) TIILNK(6415,8,8)
From: Carl A Baltrunas <Carl> 
Date: Mon, 30 Nov 87 15:13:08 PST 
To: Julie Wagner <TYM.J/WAGNER@ONTYME.Tymnet> 
Cc: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Subject: Node 10115 

As per our telephone conversation, we have no further need for node
number 10115.  The node was previously connected to node 3146 in
Fremont (Liberty street site).  The node was disconnected from TYMNET
on August 28th, 1987.

I don't know if you need our cost code number.  If so,  the code for
Field Service Company - Product Support is 90842.  The old Tymshare
cost code for our group is 4011 (whichever one is on your books).

Thank you for your help.

Carl A Baltrunas			Phone: 408-922-6206
TYMCOM-X Product Support		Mailstop: D2-325
Field Service Company
Received: from X32.Tymnet by D35.Tymnet; Mon, 30 Nov 87 22:21:37 PST
Return-path: <JMS@X32.Tymnet> 
From: Joe Smith <JMS> 
Date: Mon, 30 Nov 87 22:16:55 PST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Comment on "Zapped! Gone!" ports. 

The spare KI was running X32-P035/C05-1 which means it was loaded from tape.
When I ran TTYTAB during the day, it said two ports were "Zapped! Gone!".
Figuring that they would go away when X32-P035/C08 was loaded from NEWMON,
I ran TAKEIT to do so.  Bad move, because after TAKEIT has issued the HANG
uuo to make the system go to BOOTS, the once-a-second code in the monitor
waited forever for those two ports to go away.  I had to get an operator
to deposit 1 in 30.  This has happened once before, but should never be
seen again with /C08.   /Joe
Received: from X32.Tymnet by D35.Tymnet; Wed, 2 Dec 87 1:45:43 PST
Return-path: <Carl@X32.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Wed, 2 Dec 87 1:40:15 PST 
To: Monitor Group <CARL>, Osman Guven <Osman>, Joe Smith <JMS> 
Cc: Craig Fletcher <fletcherc>, Dennis Coffey <dencoff> 
Subject: Bug in SETE UUO 

I found a bug in the SETE UUO code introduced in /C07.  It is really a
typo and can be fixed with a 1-word patch.
   SETE+10/ XCTFU <SKIPGE 2(M)>
               should be
   SETE+10/ XCTFU <SKIPGE 2(T2)>

In /C07 & /C08 this actually reads:
   SETE+10/ XCT 1,UUOLIT+111    which contains/  SKIPGE 2(M)

I patched it on system 32 while testing the new version of SETE.
(both in the running monitor and on disk).

See MONDOC.

/Carl
Received: from X32.Tymnet by D35.Tymnet; Wed, 2 Dec 87 3:21:22 PST
Return-path: <Carl@X32.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Wed, 2 Dec 87 3:17:41 PST 
To: Monitor Group <CARL>, Osman Guven <Osman>, Joe Smith <JMS> 
Cc: Craig Fletcher <fletcherc>, Dennis Coffey <dencoff> 
Subject: /C09 

Joe, Osman... do we want to patch /C08 or rebuild everything as /C09 or
wait a few days to see if we want to change anything else before we do
anything?

Any version of SETE will die (user mode error-page fault in user space)
without the patch.  The BUG used the hash constant as the address in user
space instead of the block address, so different page faults occur based
on the passwords given by the user.

See you in the morning.

/Carl
Received: from X32.Tymnet by D35.Tymnet; Wed, 2 Dec 87 3:24:12 PST
Return-path: <Carl@X32.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Wed, 2 Dec 87 3:21:42 PST 
To: Monitor Group <CARL>, Osman Guven <Osman>, Joe Smith <JMS> 
Cc: Craig Fletcher <fletcherc>, Dennis Coffey <dencoff> 
Subject: New SETE %14 

There is a new SETE program on SYS.  I didn't bother to make it try SETE
and then SETLIC if SETE fails.  It simply checks for zero license and
expects the new monitor.  We can wait until the new monitor is running
everywhere before transmitting it.

/Carl
From: Dennis Coffey (Tymcom-X Systems) <DenCoff> 
Date: Thu, 3 Dec 87 15:01:01 PST 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: Sys 14 & 17. 

Guys:

  I just got a call from Tracy, who's at Nicholson.  The TU45s are down.  He
did not get the time to get them back up.  Probably (possibly) Friday.  He
needs to talk to Osman.  He'll call to Solar.

-D.-


P.S.  Osman:  Tracy said to let you know that he needs the sheet on the
9100.  With that info he said he'll be able to hook it up to the TU45.
Received: from X32.Tymnet by D35.Tymnet; Fri, 4 Dec 87 2:30:38 PST
Return-path: <JMS@X32.Tymnet> 
From: Joe Smith <JMS> 
Date: Fri, 4 Dec 87 2:29:14 PST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Format of customer version number. 

The following is available as item 70 of GETTAB table 11 in P035/C09 and later:
;VERMAJ is a single letter.       Currently "P"=^O20
;VERMIN is 3 decimal digits.      Currently "035"=^O43
;VERSUB (if present) is a slash followed by 1 or 2 letters /A-/Z, /AA-/AZ, etc.
;VERDEV is not present in released monitor, "01"-"99" for development.
;VERPAT (if present) is a hyphen followed by letters or decimal digits.
;Digits indicate DDT patch to SYSTEM.SAV, letters indicate source patch.
;If VERPAT has letters, it gets 256 added to it.
	A00CVN=: BYTE (6) VERMAJ (9) VERMIN (6) VERSUB (6) VERDEV (9) VERPAT

Received: from F33.Tymnet by D35.Tymnet; Fri, 4 Dec 87 14:45:25 PST
Return-path: <Carl@D35.Tymnet> 
From: Carl A Baltrunas <Carl@D35.Tymnet> 
Date: Fri, 4 Dec 87 14:28:19 PST 
To: Monitor Group <CARL@D35>, Osman Guven <Osman@D35.Tymnet>, Joe Smith
	<JMS@D35.Tymnet> 
Cc: Craig Fletcher <fletcherc@D35.Tymnet>, Dennis Coffey <dencoff@D35.Tymnet> 
Subject: XEXEC Monitor solution! 

Joe,
  I've come up with a solution to the problem XEXEC has with the universal
identifier JBTUID which currently restarts at 1 each time the system is
reloaded.  If instead of using a monotonically increasing number, we set
the UID to the universal-date-time, we will be guaranteed of unique UIDs
that will never be reused.  Thus, if a job number and UID match at any time
we know we have the right job.

  Of course, we know the UDT is accurate to 1/3 second, so what do we do
about jobs that would have the same UDT?  Simple... since we keep the last
UID, we now keep the last UDT used for a UID and if the current UDT matches,
we increment it by 1  (1/3 second isn't going to hurt anything).  It's a
small possibility that the UID could get ahead of the UDT but it wouldn't
stay ahead for very long.

  And last, but not least, we can redirect .GTJLT (130) to point to JBTUID
and be able to obtain the login time for a job.

  The change should be in FRMSER in FRMASN where the UDT is incremented and
set for each frame

*** I would like this change to be made in /C09 ***

/carl
Received: from X32.Tymnet by D35.Tymnet; Fri, 4 Dec 87 17:35:00 PST
Return-path: <JMS@X32.Tymnet> 
From: Joe Smith <JMS> 
Date: Fri, 4 Dec 87 17:29:04 PST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: Re: Format of customer version number. 

(begin forwarded message)

From: Carl A Baltrunas <Carl> 
Date: Fri, 4 Dec 87 17:20:55 PST 
To: Joe Smith <JMS> 
Subject: Re: Format of customer version number. 
In-reply-to: your message of Fri, 4 Dec 87 2:29:14 PST

...;If VERPAT has letters, it gets 256 added to it...
How do we tell the difference between P035/D-1, P035/D-A, P035/D-B, P035/D-A-1

(or however you want to specify /D-A with a ddt patch)
I realize we will never see -A, -B because it's internal, but... adding 256
... unless you mean adding 256 per letter...?

/Carl

(end forwarded message)

The current definition has 9 bits for patch level.  The macro in COMTXT
is set up to handle a numeric patch, or an alpha patch level, but not
both.  Since this number is determined at compile time, it really should
include only source patch indications; PATMAP is for numeric DDT patches.
What are Osman's and Craig's opinions on this?   /Joe
Received: from D34.Tymnet by D35.Tymnet; Fri, 4 Dec 87 17:41:00 PST
Return-path: <JMS@D34.Tymnet> 
From: Joe Smith <JMS> 
Date: Fri, 4 Dec 87 19:38:06 CST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: Suprise inspection 

Word has gotten out that Bert Novak will be in San Jose 11-Dec to maake a
site inspection.  We should get our offices and Nicholson ready.  /Joe
Received: from F74.Tymnet by D35.Tymnet; Tue, 8 Dec 87 15:47:48 PST
Return-path: <JMS@F74.Tymnet> 
From: Joe Smith <JMS> 
Date: Tue, 8 Dec 87 15:43:38 PST 
To: Rick Daniels <OPERA.SUP@EMSTXS.Ontyme> 
Cc: Monitor Group <JMS>, Carl, Osman, FletcherC 
Subject: P035/C10 

There were 2 changes to P034/C09 yesterday.
1) Output correct information on CPU stopcodes, instead of getting a
   2n stopcode in the middle of the first stopcode.
2) Fix problem where TYPBAT and other programs couldn't find DSKB1 but
   found DSKB10 twice.
The second change was not implemented correctly.  It has been fixed and
P035/C10 has been copied to NEWMON on all systems in Fremont.
Please resume loading from NEWMON.    /Joe
From: Dennis Coffey (Tymcom-X Systems) <DenCoff> 
Date: Tue, 8 Dec 87 15:59:07 PST 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: SPOOL Support. 

Guys,

  I'm a little late with this---I probably should have doen this last week.
Who will be the SPOOL maintainer?  I will get with him to give him the easiest
intro to what I've been doing to maintain SPOOL (and how I've been doing
it).  The monthly stuff can wait until near the end of the month, and this
week's stuff required no manual intervention, so I've finished it.

Till later,
-D.-
Received: from F33.Tymnet by D35.Tymnet; Wed, 9 Dec 87 14:55:59 PST
Return-path: <JMS@F33.Tymnet> 
From: Joe Smith <JMS> 
Date: Wed, 9 Dec 87 14:54:15 PST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: Keys to Lab 

Until Craig gets back and tells Security that we are authorized to have keys
to D2-610 and D2-616, I put the keys back where they were.   /Joe
Received: from X32.Tymnet by D35.Tymnet; Fri, 11 Dec 87 17:07:01 PST
Return-path: <JMS@X32.Tymnet> 
From: Joe Smith <JMS> 
Date: Fri, 11 Dec 87 17:04:58 PST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: Hotline call for wrong Software Support. 

Central Dispatch paged me, said that a customer had a software question.
The customer wanted Microdata Software Support, but got DEC Software Support.
From: Carl A Baltrunas <Carl> 
Date: Mon, 14 Dec 87 18:57:35 PST 
To: Jan Krivanec <IPC.J/Krivanec@Ontyme.Tymnet> 
Cc: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc> 
Subject: GAN-5 and other usernames 

Jan,
  There are a reasonable number of usernames that currently exist on the
PDP-10s that no one ever logs into.  Is there really any reason for those
usernames to exist in TYMNET?  Is there any reason why a set of usernames
or directories cannot exist only on the PDP-10s?

  The only stipulation being that those usernames cannot be assigned to
users that want to use the PDP-10s.  A user could have the name (DEC) and
be valid to talk to the DECNET gateways 411 and 412, but not be valid on
the PDP-10s.  On the PDP-10s we could have username (DEC) with a designated
PPN that isn't billed against (since it would be an IPC internal name).

  Maybe we should get together to talk about this... since if you and Ed
and Nancy and I can agree on what I'm proposing, it would solve the problem
with duplicate UUNs and reduce the cost incurred by IPC and by us in TYMNET.
(Why should we have billable username sin TYMNET if no one ever logs in?)

/Carl
Received: from F33.Tymnet by D35.Tymnet; Mon, 14 Dec 87 19:16:03 PST
Return-path: <JMS@F33.Tymnet> 
From: Joe Smith <JMS> 
Date: Mon, 14 Dec 87 19:13:45 PST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: LOGINN version 70.2 

LOGINN version 70.2 sets the UFD creation date to the date and time of
most recent login.  (Note that GFD does not affect this date.)  Also, the
"you have mail" message been revised.  (It's still hardcoded - LOGINN has
not been modified to read a message file yet.)  /Joe
Received: from X32.Tymnet by D35.Tymnet; Tue, 15 Dec 87 15:58:45 PST
Return-path: <Carl@X32.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Tue, 15 Dec 87 15:55:54 PST 
To: Monitor Group <CARL>, Osman Guven <Osman>, Joe Smith <JMS> 
Cc: Craig Fletcher <fletcherc>, Dennis Coffey <dencoff> 
Subject: /D01 request 

can we put a small table of "known" serial numbers and what hosts they
are supposed to represent in the monitor and when we are rrunning any
monitor on the wrong host, or wrong configuration we can see that change
in the PJ output... eg X32-58 says X32 on 58's hardware...

/carl
Received: from X17.Tymnet by D35.Tymnet; Tue, 15 Dec 87 17:58:41 PST
Return-path: <JMS@X17.Tymnet> 
From: Joe Smith <JMS> 
Date: Tue, 15 Dec 87 14:51:35 PST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: Work order for connection at Nicholson Lane. 

Project 39009.WSB 11-Dec-87
Node:6657, Site:4458, KHost:4511
Host numbers assigned: Host 15, Host 930, Host 4117.
Lines to: ND5561/HW/9.6/WS(8)8, ND5416/HW/9.6/WS(8)8

Project 39011.WSB 11-Dec-87 to be done 16-Dec
Node:6760, Site:4458, Khost:4681
Host numbers assigned: Host 16, Host 934, Host 4284, TYMbase 18813
Lines to: ND5561/HW/9.6/WS(8), ND5416/HW/9.6/WS(8)8
From: Joe Smith <JMS> 
Date: Wed, 16 Dec 87 17:19:15 CST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: Connected at last! 

6657 (X17 base) is connected to ND5416 (XRAY:3732) and ND5561 (XRAY:3734).
6760 (X14 base) is connected to ND5416 and ND5561 also.
Node 2346 has been renamed to NICK (terminals & modems at Nicholson).
Node 10115 has been renamed to FOON (dual base for the Foonlys).
Node FRED (terminal & modems at MDC) is basically unchanged.
Node 2770 now tells the Supervisor that it has hosts 62 (alias for X14),
95 (alias for X17), 118 (alias for X930), and 897 (alias for X934).
TYMNET access to 930 and 934 is via node 6760.
			/Joe
From: Joe Smith <JMS> 
Date: Wed, 16 Dec 87 21:15:57 CST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: X17 down with PAR ERR. 

X17 dies with PAR ERR when there is a lot of disk activity, such as doing a
TITO store.  It dies even when it is in CONSOLE mode.  Tracy is looking at
it.   /Joe
Received: from F29.Tymnet by D35.Tymnet; Fri, 18 Dec 87 12:31:15 PST
Return-path: <DenCoff@F29.Tymnet> 
From: Dennis Coffey <DenCoff> 
Date: Fri, 18 Dec 87 9:53:01 PST 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: Mail to me, via DenCoff. 

My old username is on a few of the public network PDP-10s.  The hosts with
DENCOFF are 25, 29, 33, 34 & 54.  My home host is B39, for general use as well
as for TUMS.

-D.-
From: Carl A Baltrunas <Carl> 
Date: Mon, 21 Dec 87 3:24:18 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc> 
Subject: Standby 

I am on standby for the next two weeks 21-Dec-87 thru 3-Jan-88.

/Carl
Received: from X17.Tymnet by D35.Tymnet; Fri, 25 Dec 87 3:41:01 PST
Return-path: <Carl@X17.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Fri, 25 Dec 87 3:37:01 PST 
To: Joe Smith <JMS>, Craig Fletcher <fletcherc>, Osman Guven <Osman> 
Subject: Out of disk space X17 

System 17 ran out of disk space....

  NOTICE  17    12772  24-DEC-87
  NOTICE  74     6777  24-DEC-87

I deleted these two files and got 19,549 pages back.  These files
contained very little on page 1, and thousands of pages of nulls!!!


No idea why it happenned...

/Carl
Received: from X17.Tymnet by D35.Tymnet; Tue, 29 Dec 87 16:38:22 PST
Return-path: <Carl@X17.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Tue, 29 Dec 87 16:28:07 PST 
To: Monitor Group <CARL>, Osman Guven <Osman>, Joe Smith <JMS> 
Cc: Craig Fletcher <fletcherc> 
Subject: X17 out of room again! 

I tried logging into X17 today and found it "job capacity exceeded"
went to Nicholson and found, "disk full, take corrective action" and
cty was out of paper...

I reloaded and found 2 files in (M33:17), XFER.WED was 8281 and XFER.FRI
was 4582 pages long...

It appears we are having some kind of "open-line" problem with aux-circuits
where lots of nulls are "sent"/"received" and they are filling system 17 so
it is running out of space...  there is approx 20,000 pages free on the
system at the moment... (of course, there was this much free on XMAS day
also, but the problem occurred again!)

/Carl
   wEbx.