Received: from F29.Tymnet by D35.Tymnet; Mon, 24 Aug 87 17:30:09 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 24 Aug 87 14:28:15 PDT
From: TYMPLN.HQ@EMSTXS.Ontyme.Tymnet 
Date: 24 AUG 87 19:56:15 
To: TXSSUP@D35.Tymnet 
Message-id: M14190@Ontyme.Tymnet 
Subject: ACCESS CHARGE SEMINAR 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Mon, 24 Aug 87 19:54:55 CDT 
Resent-to: JMS, OSMAN, CARL, DENCOFF, FLETCHERC 

                           T Y M N E T

           MC DONNELL DOUGLAS NETWORK SYSTEMS COMPANY

                       M E M O R A N D U M


   DATE:  AUGUST 24, 1987

     TO:  ALL TYMNET MANAGERS & ALL SALES

   FROM:  JO AN COUCHE

SUBJECT:  ACCESS CHARGE SEMINAR
__________________________________________________________________




               * * ACCESS CHARGE UPDATE * *



Access charges -

  What are they?

  Why does the FCC want to impose them on Tymnet?

  How will they impact our business?

  What can we do to stop the FCC from imposing these charges?


These  questions  and  many more will be answered at  the  Access
Charge  Seminar  on  Thursday,  August 27 9:00-11:00  AM  in  the
Training Room at Valley Green Drive

Please plan to attend.  Contact Jo An Couche at (408) 446-7154 if
you have questions.
Received: from F29.Tymnet by D35.Tymnet; Mon, 31 Aug 87 11:44:10 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 31 Aug 87 11:36:15 PDT
From: IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet 
Date: 31 AUG 87 19:34:00 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A07141@Ontyme.Tymnet 
Subject: System D-27 Memo 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Thu, 10 Sep 87 22:46:21 CDT 
Resent-to: FLETCHERC 
D-27UserMove: 

   Date:  August 31, 1987
     
     To:  All INTERNAL D-27 User's 
     
   From:  Resource Planning & Management
          Jan Krivanec   
     
Subject:  D-27 User Move 
     
 Reason:  System D-27 Shutdown
     
-------------------------------------------------------------------------  
     
     
System D-27 will be permanently shutdown on September 31, 1987. RPM   
has chosen to route all D-27 User's to System D-34 by September 26, 1987.  
     
If you are valid on D-27 and D-34 you are requested to move your own  
files and tapes to D-34. You are to be completed by September 26, 1987.    
     
If you are valid only on D-27, RPM and Operations will move your files
and tapes to D-34. This request will begin September 25, 1987 beginning    
at 1800 pst.   
     
If you have any questions, please call me at (415) 498-2556 or ontyme 
IPC.J/KRIVANEC.


Thank you,
Jan Krivanec
Received: from F29.Tymnet by D35.Tymnet; Wed, 2 Sep 87 7:47:33 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 2 Sep 87 7:45:26 PDT
From: ISGFM.R/KAMINSKI@EMSTXS.Ontyme.Tymnet 
Date: 02 SEP 87 15:31:10 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: J11985@Ontyme.Tymnet 
Subject: "ADMINISTRATIVE NO: DIS-87-012"... 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Thu, 10 Sep 87 22:46:39 CDT 
Resent-to: FLETCHERC 




                                ADMINISTRATIVE          NO:    DIS-87-012
                                    BULLETIN            DATE:  02 SEP 87

         MCDONNELL DOUGLAS DIVERSIFIED INFORMATION SYSTEMS COMPANY



To:                ISG St. Louis Tract III Lists A - H

Subject:           EXPRESS SHIPPING SERVICES



Effective September 1, 1987, the processing of expedite/express parcels
previously handled by Production Services, Information Processing Company
has been transferred to the Metropolitan Services Organization.  The
function and the receiving window has been relocated from Building 307,
1 West to Building 307, 1 East.

The basic services previously provided will continue at the new location.
Hours of operation will be changed effective September 7, 1987 to
8:30 a.m. to 4:30 p.m., Monday through Friday.  Therefore, all parcels
must be to the MSO before 4:30 p.m.

We continue to look forward to being of service to you in this area of
responsibility.


(Original signed by M. J. Daniels)

M. J. Daniels, Manager
Branch Center Tract III
Metropolitan Services Organization - St. Louis


(Original signed by R. W. Brown)

R. W. Brown, Manager
Production Services
Information Processing Services


(Original signed by R. D. Windsor)

R. D. Windsor, Director
Metropolitan Services Organization - St. Louis
From: Joe Smith <JMS@D35> 
Date: Tue, 1 Sep 87 18:21:41 CDT 
To: fletcherc 
Cc: Monitor Group <JMS>, Carl, Osman, FletcherC, DenCoff 
Subject: A Varian PDP-10 Base in the Augment area. 
Resent-from: Joe Smith <JMS@D35> 
Resent-date: Thu, 10 Sep 87 22:47:51 CDT 
Resent-to: FLETCHERC 

There is an orange PDP-10 dual base complete with "72" CPU in the Augment
junk area at Liberty Street.  It looks to be the base for V70 and V72 from
Valley Forge.  I don't think it belongs in the Augment area.  Shouldn't it
be moved to FSC or IPC property?  /Joe
Received: from X32.Tymnet by D35.Tymnet; Mon, 14 Sep 87 18:16:12 PDT
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Mon, 14 Sep 87 18:14:16 PDT 
To: Ed Barens <IPC.E/Barens@Ontyme>, Jim English <IPC.J/English@Ontyme>, Leland
	Yarbrough <IPC.L/Yarbrough@Ontyme>, Tom Marconi <IPC.T/Marconi@Ontyme>,
	Bill Fischer <IPC.B/Fischer@Ontyme>, Cheryl Eldred
	<IPC.C/Eldred@Ontyme>, Rick Daniels <IPC.R/Daniels@Ontyme>, Bill
	Richardson <FSC.B/Richardson@Ontyme>, Jerry Meyer <FSC.G/Meyer@Ontyme>,
	Ray Donahue <FSC.R/Donahue@Ontyme>, Steve Atwell <FSC.S/Atwell@Ontyme>,
	Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: AR/ARX Parity Error .. 





                                                           Sept 11, 1987


                            AR/ARX Parity Error
                            -------------------

	Any system running with the P035/C monitor if enabled will
report the AR/ARX parity error.  This would give FSCO personnel more
precise information where in the hardware the error happened.

	AR/ARX parity error checking is enabled by KLDCP.  While
in KLDCP type "PE 36<cr>" to enable it and "PE 16<cr>" to disable it.
Once the AR/ARX parity error checking is enabled on the KL10 you must
bring the system up with P035/C monitor or later.

Any question or comment:
OSMAN         =  PDP10 User name
FSC.O/GUVEN   =  Ontyme user name
Phone: (415)922-6236

-Osman-
Received: from F29.Tymnet by D35.Tymnet; Fri, 11 Sep 87 16:44:26 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Fri, 11 Sep 87 16:25:30 PDT
From: QSATS.G/KOLEK@EMSTXS.Ontyme.Tymnet 
Date: 11 SEP 87 23:46:27 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M18544@Ontyme.Tymnet 
Subject: NEW ADDRESS AND PHONE NUMBERS FOR QSATS 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Wed, 16 Sep 87 1:35:27 CDT 
Resent-to: JMS, OSMAN, CARL, DENCOFF, FLETCHERC 
NEWADDRESS/TELEPHONENUMBERS: 

                                     MEMORANDUM
                               NETWORK SYSTEMS COMPANY
                       QUALITY SERVICES AND TECHNICAL SUPPORT

          TO:       DISTRIBUTION                       CC:  DON JOHNSON
          FROM:     GLORIA KOLEK                            GARY WALKER
          DATE:     11 SEPTEMBER 1987                       ROURKE McCUSKER
          SUBJECT:  NEW ADDRESS/TELEPHONE NUMBERS:
                    (QSATS) N.T.S., S.T.S, Q.A.
          _________________________________________________________________

          NEW ADDRESS FOR U.S. MAIL DELIVERY:
          McDONNELL DOUGLAS CENTER
          (DEPT OR EMPLOYEE NAME + MAIL STOP)  HTS, STS, QA: M.S. F-2
          2560 N. FIRST STREET
          P. O. BOX 49019
          SAN JOSE, CA 95161-9019

          NEW ADDRESS FOR PRIVATE DELIVERY SERVICE (UPS, FED-EX, DHL, ETC)
          McDONNELL DOUGLAS CENTER
          (DEPT OR EMPLOYEE NAME + MAIL STOP)  HTS, STS, QA: M.S. F-2
          2560 N. FIRST STREET
          SAN JOSE, CA 95131

          TELEPHONE LISTING FOR QSATS (HTS, STS, QA):
          AREA CODE: 408      PREFIX NUMBER FOR ALL EXTENSIONS: 922

          NAME________________     DEPARTMENT__________________  EXTENSION
          AKELLA, RAM              QUALITY ASSURANCE             7461
          ARNETT, MARY             QUALITY ASSURANCE             7462
          BUBSEY, GAIL             STS (INTERFACE SUPPORT)       7463
          BURROUGH, JOHN           STS (INTERFACE SUPPORT)       7464
          CATTANEO, AUGUST         NTS (H/W TECH. SUPPORT)       7466
          CHEN, BEN                STS (NETWORK SUPPORT)         7468
          CHENG, HENRY             QUALITY ASSURANCE             7470
          CHIANG, SHIRLEY          STS (INTERFACE SUPP, MGR)     7471
          CHU, PING                STS (INTERFACE SUPPORT)       7472
          CLARIDGE, JON            QUALITY ASSURANCE             7473
          CURRI, LOUISE            STS (STS TECH. ANALYST)       7477
          DIAS, LARRY              QUALITY ASSURANCE             7478
          ELLG, DOUG          STS (APPLICATIONS SUPP, MGR)  7480
          FISTE, TOD               STS (INTERFACE SUPPORT)       7484
          HO, RICHARD              STS (INTERFACE SUPPORT)       7486
          HOUGE, DIANA             QUALITY ASSURANCE             7487
          HUSSEY, DAVE             QUALITY ASSURANCE             7489
          JOHNSON, DON             QSATS (NTS, QA, MANAGER       6222
          KOCHMANN, TIM            NTS (H/W TECH. SUPPORT)       7493
          KOLEK, GLORIA            QSATS (NTS, STS, QA, SECY)    7495
          KRUMVIEDE, PAUL          NTS (H/W, S/W DIAG. SUPPORT)  7496
          LANGDON, CARL            STS (NETWORK SUPP, MGR)       7497
          LIU, JEFF                STS (APPLICATIONS SUPPORT)    7498
          LUCAS, JERRY             STS (NETWORK SUPPORT)         7499
          MATUCHA, DEAN            QUALITY ASSURANCE             7500
          McKIERNAN, JOHN          STS (INTERFACE SUPPORT)       7501












          MISTRY, PRAVIN           QUALITY ASSURANCE             7502
          MOORING, ED              NTS (H/W, S/W, DIAG. SUPPORT) 7504
          NARAYAN, KRISHNAN        STS (APPLICATIONS SUPPORT)    7507
          NELSON, PHIL             NTS (H/W TECH. SUPPORT)       7508
          NILLUKA, SANDRA          STS (NETWORK SUPPORT)         7510
          REILLY, JOHN             STS (NETWORK SUPPORT)         7447
          RICHARDS, STAN           NTS (H/W TECH. SUPPORT)       7513
          ROWE, CLIVE              STS (NETWORK SUPPORT)         7514
          SHARMA, ALOK             STS (INTERFACE SUPPORT)       7516
          SHEPHERD, BRUCE          NTS (H/W TECH. SUPPORT)       7517
          SHUTICH, JOHN            NTS (H/W TECH. SUPPORT)       7069
          STEIN, JIM               NTS (H/W TECH. SUPPORT, MGR)  7518
          TURNER, TOM              QUALITY ASSURANCE             7520
          VIVIER, RON              NTS (H/W S/W DIAG SUPP, MGR)  7521
          WALKER, GARY             STS (APPL,NW,INTERFACE, MGR)  7523
          WANG, JAMES              STS (NETWORK SUPPORT)         7524
          WARNER, RUTH             QUALITY ASSURANCE             7525
          YEH, TED                 STS (APPLICATIONS SUPPORT)    7528


          NOTE #1:
          FIELD ENGINEERING HANDBOOK IS COMPLETE AND AVAILABLE TO ORDER.
          PLEASE CONTACT YOUR MANAGER FOR FURTHER DETAILS.


          NOTE #2:
          DUE TO "CIRCUMSTANCES BEYOND OUR CONTROL", OUR MOVE HAS BEEN
          DELAYED FOR ONE WEEK.  WE WERE ORIGINALLY SCHEDULED TO MOVE ON
          FRIDAY, 11 SEPTEMBER 1987; OUR NEW MOVING DATE IS TARGETED FOR
          FRIDAY, 18 SEPTEMBER 1987.  ANY AIL BY U.S. POSTAL SERVICE OR
          PRIVATE MAIL CARRIER WILL BE DELIVERED TO NEW MAILING ADDRESS
          AND REROUTED TO ORCHARD PARKWAY.

          PRESENT TELEPHONE NUMBERS FOR NTS,  STS AND QA  ARE  STILL  VALID
          UNTIL FURTHER NOTICE.

          WHEN  TELEPHONE  NUMBERS  ARE  CHANGED,  AND  YOU  PHONE  OUR OLD
          NUMBERS, THERE WILL BE A RECORDED MESSAGE STATING THAT THESE
          NUMBERS HAVE BEEN DISCONNECTED AND YOU WILL BE GIVEN A NEW NUMBER
          TO USE.

          VOICE MAIL WILL REMAIN ACTIVATED ON OLD TELEPHONE NUMBERS FOR ONE
         WEEK AFTER TELEPHONE NUMBERS ARE CHANGED.

          IF IN DOUBT, PLEASE CALL CORPORATE TELEPHONE OPERATOR AT
          (408) 922-0250.
From: Joe Smith <JMS@X32> 
Date: Wed, 16 Sep 87 1:49:04 CDT 
To: OSMAN, DENCOFF 
Cc: carl, fletcherc 
Subject: C compiler 

(begin forwarded message)

Received: from B39.Tymnet by D35.Tymnet; Tue, 15 Sep 87 23:46:14 PDT
Received: from tymix.Tymnet by B39.Tymnet; Mon, 7 Sep 87 20:14:25 PDT
Received: by tymix.Tymnet (5.51/4.7) id AA23404; Mon, 7 Sep 87 20:15:48 PDT
Received: by hobbes.Tymnet.com (3.2/SMI-3.2) id AA15598; Mon, 7 Sep 87 20:15:46
	PDT
Return-path: <wrs@hobbes> 
From: wrs@hobbes (Bill Soley) 
Date: Mon, 7 Sep 87 20:15:46 PDT 
To: carl@D35, jms@D35 
Message-id: <8709080315.AA15598@hobbes.Tymnet.com> 
Subject: C compiler 

I've found sources for a Tops-20 C compiler on one of the MIT machines.
Is anyone interested?  -Bill

(end forwarded message)

I think we could get Marc Crispin to write a tape at Stanford, if there is
sufficient interest.  /Joe
From: Joe Smith <JMS@X32> 
Date: Wed, 16 Sep 87 8:33:38 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: MUX 2096 is very slow today. 

As of 9/15, MUX hosts 2096 and 1274 have moved from Engines in Orchard Parkway
to Microengines in South Bay Center.  If you have nodes 2366 or 2367 in your
SWITCH.INI, they should be changed to 3170 and 3345 respectively.  I noticed
the change because host 2096 was having problems.  It was "2*OV" and "****"
meaning the link to its only neighbor was overloaded both directions and
had a high line error rate.  1274 was better.   /Joe
From: Joe Smith <JMS@X32> 
Date: Wed, 16 Sep 87 8:40:36 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: [1, 4].UFD damaged on F26. 

The first UFD data page for (SYS:26) was on BPA3 page 10010.  That was one
of the pages that PAKCOP could not read, and had pointers to LOGINN and RPG.
DSKCLN aborted with "Error in RIB - wrong hash code" and "Critical file
damaged".  Page 0 was indeed garbage, and the 2nd page for that hash code
was 10.  After zeroing the offending paged and putting 10 in the link at 777,
the UFD was readable.  Having REFLAG, I restored all of SYS until TITO asked
to overwrite a file.  Typing control-C at that point caused TITO to report
that 102 files were processed, exactly one page worth.  F26 is running a
full DSKCLN at this moment.  /Joe
From: Carl A Baltrunas <Carl> 
Date: Thu, 17 Sep 87 0:58:34 PDT 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Subject: 98% dialup connection 

I sent mail on X14 describing the events, but you won't see them until you
get to the office.  I returned to the office around 7:30 and generated new
code at Nicholson, reloaded 2346, went to SBC to install the new boards,
went back to Nicholson to get a 2nd DUV11 for 2770, back to SBC to install
it, back to Nicholson to load 2770, back to SBC to check the DZV11 and the
node itself, re-pinned 4 male connectors as cross-overs at the DZV11 panel
and connected the modem with a straight male connector.

The modem line works... however, the code is generated with the DZV11 lines
as Hard-Wired and I need to change the configuration to Dial-Up and reload
2770.  I will try to do that on my way to the office tomorrow (today).  I
will check to see who is on before I yank out the plug on 2770, besides I
will need someone to push the HALT/ENABLE and INIT buttons to put it into
it's bootstrap to load.  (I don't remember how to do it remotely).

I am logged in on the modem, and even though I hung up, the modem will not
because the line isn't a dial-up... this should be fixed when I reload it.
Possibly if I logged out first, the modem would drop the circuit... but that
isn't the case.  I just hung up.

/Carl
@8